global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "rating-service"
    static_configs:
      - targets: ["rating-service:80"]

  - job_name: "accommodation-service"
    static_configs:
      - targets: ["accommodation-service:80"]

  - job_name: "reservation-service"
    static_configs:
      - targets: ["reservation-service:80"]

  - job_name: "search-service"
    static_configs:
      - targets: ["search-service:80"]

  - job_name: "user-service"
    static_configs:
      - targets: ["user-service:80"]

  - job_name: "notification-service"
    static_configs:
      - targets: ["notification-service:80"]
