global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "rating-service"
    static_configs:
      - targets: ["host.docker.internal:5003"]

  - job_name: "accommodation-service"
    static_configs:
      - targets: ["host.docker.internal:5002"]

  - job_name: "reservation-service"
    static_configs:
      - targets: ["host.docker.internal:5004"]

  - job_name: "search-service"
    static_configs:
      - targets: ["host.docker.internal:5005"]

  - job_name: "user-service"
    static_configs:
      - targets: ["host.docker.internal:5001"]

  - job_name: "notification-service"
    static_configs:
      - targets: ["host.docker.internal:5006"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
