global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'rating-service'
    static_configs:
      - targets: ['rating-service:8080']

  - job_name: 'accommodation-service'
    static_configs:
      - targets: ['accommodation-service:8080']

  - job_name: 'reservation-service'
    static_configs:
      - targets: ['reservation-service:8080']

  - job_name: 'search-service'
    static_configs:
      - targets: ['search-service:8080']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8080']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
